###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"samuel",
    "username":"sam123",
    "password": "sam@123",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"sam123",
    "password": "sam@123"
}